feat: get working with two-chainz scenario
./scripts/init-chainz --help
./scripts/init-chainz gaia agoric
./run-chainz &
./link-chainz

diff --git a/scripts/init-chainz b/scripts/init-chainz
--- a/scripts/init-chainz
+++ b/scripts/init-chainz
@@ -7,7 +7,6 @@ DEFAULT_CONFIG=gaia
 RELAYER_DIR=$(cd "$thisdir/.." && pwd)
 CONFIGS_DIR="$RELAYER_DIR/configs"
 DATA="$PWD/data"
-CONFFILES=( demo.json )
 
 CHAIN_RE='^([^=]+)=(.+)$'
 LINK_RE='^([^:]+):([^:]+)$'
@@ -48,6 +47,23 @@ JSONS=()
 SRCS=()
 DSTS=()
 
+get_alpha() {
+  id="$1"
+  ida=$(echo "$1" | sed -e 's/0/zero/g; s/1/one/g; s/2/two/g; s/3/three/g; s/4/four/g; s/5/five/g; s/6/six/g; s/7/seven/g; s/8/eight/g; s/9/nine/g;')
+}
+
+get_port() {
+  id="$1"
+  for i in ${!IDS[@]}; do
+    if [[ ${IDS[$i]} == $id ]]; then
+      port=$(eval echo $(jq '."port-id"' ${JSONS[$i]}))
+      return
+    fi
+  done
+  echo "$progname: cannot locate \`$id' in chain ids list"
+  exit 1
+}
+
 validate() {
   status=0
   # Have at least one default.
@@ -72,7 +88,7 @@ validate() {
       id=${BASH_REMATCH[1]}
       config=${BASH_REMATCH[2]}
       IDS+=( "$id" )
-      json=$CONFIGS_DIR/$config/chain.json
+      json=$CONFIGS_DIR/$config/chainz.json
       if [[ ! -f $json ]]; then
         echo 1>&2 "$progname: error: CHAIN \`$chain' config \`$json' does not exist"
         status=1
@@ -202,6 +218,18 @@ case $do_commit in
   ;;
 esac
 
+# Ensure user understands what will be deleted
+if [[ -d chainz ]]; then
+  read -p "$0 will delete chainz folder. Do you wish to continue? (y/n): " -n 1 -r
+  echo
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+      exit 1
+  fi
+fi
+
+rm -rf chainz
+
+
 # Fail on error.
 set -e
 
@@ -228,9 +256,8 @@ fi
 
 EOF
 
+# Global variables for run-chainz.
 cat >>"$run" <<EOF
-GAIA_REPO="$GOPATH/src/github.com/cosmos/gaia"
-GAIA_BRANCH=ibc-alpha
 DATA="$DATA"
 EOF
 
@@ -246,7 +273,7 @@ if [[ -d $DATA ]] && [[ ! "$2" == "skip" ]]; then
       exit 1
   fi
 fi
-rm -rf "$DATA" &> /dev/null
+rm -rf "$DATA"
 
 echo "mkdir $DATA"
 mkdir -p "$DATA"
@@ -326,6 +353,56 @@ wait
 EOF
 chmod +x "$run"
 
+mkdir -p chainz
+for i in ${!IDS[@]}; do
+  id=${IDS[$i]}
+  json=${JSONS[$i]}
+  p26657=$(( 26657 - $i * 100 ))
+  out="chainz/$id.json"
+  echo "creating $out"
+  jq ".link + { \"chain-id\": \"$id\", \"rpc-addr\": \"http://localhost:$p26657\", \"key\": \"testkey\" }" "$json" \
+    > "$out"
+done
+
+for i in ${!SRCS[@]}; do
+  src=${SRCS[$i]}
+  get_port "$src"
+  srcport=$port
+  get_alpha "$src"
+  srca=$ida
+
+  dst=${DSTS[$i]}
+  get_port "$dst"
+  dstport=$port
+  get_alpha "$dst"
+  dsta=$ida
+
+  demo="$srca$dsta"
+  out="chainz/$demo.json"
+  echo "creating $out"
+  cat >"$out" <<EOF
+{
+  "src": {
+    "chain-id": "$src",
+    "client-id": "${dsta}client",
+    "connection-id": "${dsta}link",
+    "channel-id": "${dsta}xfer",
+    "port-id": "$dstport"
+  },
+  "dst": {
+    "chain-id": "$dst",
+    "client-id": "${srca}client",
+    "connection-id": "${srca}link",
+    "channel-id": "${srca}xfer",
+    "port-id": "$srcport"
+  },
+  "strategy": {
+    "type": "naive"
+  }
+}
+EOF
+done
+
 ######################
 # Create link-chainz
 
@@ -363,34 +440,52 @@ if [[ -d $RELAYER_CONF ]] && [[ ! "$1" == "skip" ]]; then
   fi
 fi
 
-cd $RELAYER_DIR
-rm -rf $RELAYER_CONF &> /dev/null
+cd "$RELAYER_DIR"
+rm -rf "$RELAYER_CONF"
 
 echo "Building Relayer..."
 make install
 
 echo "Generating rly configurations..."
 rly config init
-rly config add-dir configs/agoric/
+rly config add-dir chainz/
+EOF
 
-SEED0=$(jq -r '.secret' $DATA/ibc0/n0/ag-cosmos-helper/key_seed.json)
-SEED1=$(jq -r '.secret' $DATA/ibc1/n0/ag-cosmos-helper/key_seed.json)
-echo 
-echo "Key $(rly keys restore ibc0 testkey "$SEED0") imported from ibc0 to relayer..."
-echo "Key $(rly keys restore ibc1 testkey "$SEED1") imported from ibc1 to relayer..."
-echo
-echo "Creating lite clients..."
-echo
-sleep 3
-rly lite init ibc0 -f
-rly lite init ibc1 -f
+for i in ${!IDS[@]}; do
+  id=${IDS[$i]}
+  cat >>"$link" <<EOF
 
-echo "Starting 'rly tx link demo' (ibc0<>ibc1) logs in data/zeroone.log"
-rly tx link demo --timeout=3s 2>&1 > data/demo.log &
-sleep 1
+chainid="$id"
+EOF
+  cat >>"$link" <<\EOF
+SEED=$(jq -r '.secret' "$DATA/$chainid/n0/ag-cosmos-helper/key_seed.json")
+echo "Key $(rly keys restore $chainid testkey "$SEED") imported from $chainid to relayer..."
+echo "Creating lite client for $chainid..."
+rly lite init $chainid -f
+EOF
+done
+
+for i in ${!SRCS[@]}; do
+  src=${SRCS[$i]}
+  get_alpha "$src"
+  srca=$ida
+
+  dst=${DSTS[$i]}
+  get_alpha "$dst"
+  dsta=$ida
+
+  demo="$srca$dsta"
+  cat >>"$link" <<EOF
+
+echo "Starting 'rly tx link $demo' ($src<>$dst) logs in data/$demo.log"
+rly tx link $demo --timeout=3s -d 2>&1 > data/$demo.log &
+EOF
+done
+
+cat >>"$link" <<EOF
 
 echo "Check the state of the connections using 'rly paths list' to see when they are ready to relay over..."
-rly paths list
+(while sleep 5; do rly paths list; done) &
 
 echo "Ctrl-C exits, or you can background this job..."
 wait
