Push master @jackzampolin: prep for v1.0.0-rc0 and refactor scripts to remove GOPATH per #282

diff --git a/scripts/three-chainz b/scripts/three-chainz
--- a/scripts/three-chainz
+++ b/scripts/three-chainz
@@ -1,74 +1,46 @@
 #!/bin/bash
+# two-chainz creates two gaiad chains and configures the relayer to 
 
-# Ensure gopath is set and go is installed
-if [[ ! -d $GOPATH ]] || [[ ! -d $GOBIN ]] || [[ ! -x "$(which go)" ]]; then
-  echo "Your \$GOPATH is not set or go is not installed,"
-  echo "ensure you have a working installation of go before trying again..."
-  echo "https://golang.org/doc/install"
+SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+GAIA_DATA="$(pwd)/data"
+RELAYER_DIR="$(dirname $SCRIPTDIR)"
+RELAYER_CONF="$HOME/.relayer"
+
+# Ensure gaiad is installed
+if ! [ -x "$(which gaiad)" ]; then
+  echo "Error: gaiad is not installed. Try running 'make build-gaia'" >&2
   exit 1
 fi
 
-GAIA_REPO="$GOPATH/src/github.com/cosmos/gaia"
-GAIA_BRANCH=gaiav3.0
-GAIA_DATA="$(pwd)/data"
+# Display software version for testers
+echo "GAIA VERSION INFO:"
+gaiad version --long
 
-# ARGS: 
-# $1 -> local || remote, defaults to remote
+# Ensure jq is installed
+if [[ ! -x "$(which jq)" ]]; then
+  echo "jq (a tool for parsing json in the command line) is required..."
+  echo "https://stedolan.github.io/jq/download/"
+  exit 1
+fi
 
 # Ensure user understands what will be deleted
-if [[ -d $GAIA_DATA ]] && [[ ! "$2" == "skip" ]]; then
-  read -p "$0 will delete \$(pwd)/data folder. Do you wish to continue? (y/n): " -n 1 -r
-  echo 
+if [[ -d $GAIA_DATA ]] && [[ ! "$1" == "skip" ]]; then
+  read -p "$(basename $0) will delete \$(pwd)/data and \$HOME/.relayer folders. Do you wish to continue? (y/n): " -n 1 -r
+  echo
   if [[ ! $REPLY =~ ^[Yy]$ ]]; then
       exit 1
   fi
 fi
 
+# Delete data from old runs
 rm -rf $GAIA_DATA &> /dev/null
+rm -rf $RELAYER_CONF &> /dev/null
+
+# Stop existing gaiad processes
 killall gaiad &> /dev/null
+killall akash &> /dev/null
 
 set -e
-
-
-if [[ -d $GAIA_REPO ]]; then
-  cd $GAIA_REPO
-
-  # remote build syncs with remote then builds
-  if [[ "$1" == "local" ]]; then
-    echo "Using local version of github.com/cosmos/gaia"
-    make install &> /dev/null
-  else
-    echo "Building github.com/cosmos/gaia@$GAIA_BRANCH..."
-    if [[ ! -n $(git status -s) ]]; then
-      # sync with remote $GAIA_BRANCH
-      git fetch --all &> /dev/null
-
-      # ensure the gaia repository successfully pulls the latest $GAIA_BRANCH
-      if [[ -n $(git checkout $GAIA_BRANCH -q) ]] || [[ -n $(git pull origin $GAIA_BRANCH -q) ]]; then
-        echo "failed to sync remote branch $GAIA_BRANCH"
-        echo "in $GAIA_REPO, please rename the remote repository github.com/cosmos/gaia to 'origin'"
-        exit 1
-      fi
-
-      # install
-      make install &> /dev/null
-
-      # ensure that built binary has the same version as the repo
-      if [[ ! "$(gaiad version --long 2>&1 | grep "commit:" | sed 's/commit: //g')" == "$(git rev-parse HEAD)" ]]; then
-        echo "built version of gaiad commit doesn't match"
-        exit 1
-      fi 
-    else
-      echo "uncommited changes in $GAIA_REPO, please commit or stash before building"
-      exit 1
-    fi
-    
-  fi 
-else 
-  echo "$GAIA_REPO doesn't exist, and you may not have have the gaia repo locally,"
-  echo "if you want to download gaia to your \$GOPATH try running the following command:"
-  echo "mkdir -p $(dirname $GAIA_REPO) && git clone git@github.com:cosmos/gaia $GAIA_REPO"
-fi
 
 chainid0=ibc-0
 chainid1=ibc-1
@@ -76,10 +48,31 @@ chainid2=ibc-2
 
 echo "Generating gaia configurations..."
 mkdir -p $GAIA_DATA && cd $GAIA_DATA && cd ../
-./scripts/one-chain $chainid0 ./data 26657 26656 6060 9090
-./scripts/one-chain $chainid1 ./data 26557 26556 6061 9091
-./scripts/one-chain $chainid2 ./data 25557 25556 6062 9092
+./scripts/one-chain gaiad $chainid0 ./data 26657 26656 6060 9090
+./scripts/one-chain gaiad $chainid1 ./data 26557 26556 6061 9091
+./scripts/one-chain gaiad $chainid2 ./data 25557 25556 6062 9092
 
 [ -f $GAIA_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $GAIA_DATA/$chainid0.log to see its execution."
 [ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $GAIA_DATA/$chainid1.log to see its execution."
-[ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid2 initialized. Watch file $GAIA_DATA/$chainid2.log to see its execution."
+[ -f $GAIA_DATA/$chainid2.log ] && echo "$chainid2 initialized. Watch file $GAIA_DATA/$chainid2.log to see its execution."
+
+cd $RELAYER_DIR
+
+echo "Building Relayer..."
+make install
+
+echo "Generating rly configurations..."
+rly config init
+rly config add-dir configs/three/
+
+SEED0=$(jq -r '.mnemonic' $GAIA_DATA/ibc-0/key_seed.json)
+SEED1=$(jq -r '.mnemonic' $GAIA_DATA/ibc-1/key_seed.json)
+SEED2=$(jq -r '.mnemonic' $GAIA_DATA/ibc-2/key_seed.json)
+echo "Key $(rly keys restore ibc-0 testkey "$SEED0") imported from ibc-0 to relayer..."
+echo "Key $(rly keys restore ibc-1 testkey "$SEED1") imported from ibc-1 to relayer..."
+echo "Key $(rly keys restore ibc-2 testkey "$SEED2") imported from ibc-2 to relayer..."
+echo "Creating light clients..."
+sleep 3
+rly light init ibc-0 -f
+rly light init ibc-1 -f
+rly light init ibc-2 -f
