WIP debugging denoms

diff --git a/scripts/two-chainz-akash b/scripts/two-chainz-akash
--- a/scripts/two-chainz-akash
+++ b/scripts/two-chainz-akash
@@ -11,7 +11,9 @@ if [[ ! -d $GOPATH ]] || [[ ! -d $GOBIN ]] || [[ ! -x "$(which go)" ]]; then
 fi
 
 GAIA_REPO="$GOPATH/src/github.com/cosmos/gaia"
+AKASH_REPO="$GOPATH/src/github.com/ovrclk/akash"
 GAIA_BRANCH=stargate-4
+AKASH_BRANCH=jack/ibc
 GAIA_DATA="$(pwd)/data"
 
 # ARGS:
@@ -28,6 +30,7 @@ fi
 
 rm -rf $GAIA_DATA &> /dev/null
 killall gaiad &> /dev/null
+killall akash &> /dev/null
 
 set -e
 
@@ -43,7 +46,7 @@ if [[ -d $GAIA_REPO ]]; then
     echo "Building github.com/cosmos/gaia@$GAIA_BRANCH..."
     if [[ ! -n $(git status -s) ]]; then
       # sync with remote $GAIA_BRANCH
-      git fetch --all &> /dev/null
+      git fetch --all #&> /dev/null
 
       # ensure the gaia repository successfully pulls the latest $GAIA_BRANCH
       if [[ -n $(git checkout $GAIA_BRANCH -q) ]] || [[ -n $(git pull origin $GAIA_BRANCH -q) ]]; then
@@ -72,13 +75,53 @@ else
   echo "mkdir -p $(dirname $GAIA_REPO) && git clone git@github.com:cosmos/gaia $GAIA_REPO"
 fi
 
+if [[ -d $AKASH_REPO ]]; then
+  cd $AKASH_REPO
+
+  # remote build syncs with remote then builds
+  if [[ "$1" == "local" ]]; then
+    echo "Using local version of github.com/ovrclk/akash"
+    make install &> /dev/null
+  else
+    echo "Building github.com/ovrclk/akash@$AKASH_BRANCH..."
+    if [[ ! -n $(git status -s) ]]; then
+      # sync with remote $AKASH_BRANCH
+      git fetch --all &> /dev/null
+
+      # ensure the akash repository successfully pulls the latest $AKASH_BRANCH
+      if [[ -n $(git checkout $AKASH_BRANCH -q) ]] || [[ -n $(git pull origin $AKASH_BRANCH -q) ]]; then
+        echo "failed to sync remote branch $AKASH_BRANCH"
+        echo "in $AKASH_REPO, please rename the remote repository github.com/ovrclk/akash to 'origin'"
+        exit 1
+      fi
+
+      # install
+      make install &> /dev/null
+
+      # ensure that built binary has the same version as the repo
+      if [[ ! "$(akash version --long 2>&1 | grep "commit:" | sed 's/commit: //g')" == "$(git rev-parse HEAD)" ]]; then
+        echo "built version of akash commit doesn't match"
+        exit 1
+      fi
+    else
+      echo "uncommited changes in $AKASH_REPO, please commit or stash before building"
+      exit 1
+    fi
+
+  fi
+else
+  echo "$AKASH_REPO doesn't exist, and you may not have have the akash repo locally,"
+  echo "if you want to download akash to your \$GOPATH try running the following command:"
+  echo "mkdir -p $(dirname $AKASH_REPO) && git clone git@github.com:ovrclk/akash $AKASH_REPO"
+fi
+
 chainid0=ibc0
 chainid1=ibc1
 
 echo "Generating gaia configurations..."
 mkdir -p $GAIA_DATA && cd $GAIA_DATA && cd ../
 ./scripts/one-chain $chainid0 ./data 26657 26656 6060 9090
-./scripts/one-chain $chainid1 ./data 26557 26556 6061 9091
+./scripts/one-chain-akash $chainid1 ./data 26557 26556 6061 9091
 
-[ -f $GAIA_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $GAIA_DATA/$chainid0.log to see its execution."
-[ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $GAIA_DATA/$chainid1.log to see its execution."
+[ -f $GAIA_DATA/$chainid0.log ] && echo "$chainid0 (gaiad) initialized. Watch file $GAIA_DATA/$chainid0.log to see its execution."
+[ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid1 (akash) initialized. Watch file $GAIA_DATA/$chainid1.log to see its execution."
